### mostrar home
GET http://localhost:3000

### Mostrar todos  los contenidos
GET http://localhost:3000/contenido

### Mostrar contenido por id
GET http://localhost:3000/contenido/44

### Mostrar contenido con sus actores
GET http://localhost:3000/contenido/44/actores

### filtar contenido por su nombre,mayuscula,minuscula,parcial
GET http://localhost:3000/contenido/name/crow

### Mostrar los contenido de un actor en especifico po su id
GET http://localhost:3000/contenido/actor/31

### filtar contenido por su genero
GET http://localhost:3000/contenido/genero/3

### filtar contenido por su categoria
GET http://localhost:3000/contenido/categorias/1
### filtar contenido por su nombre de genero
GET http://localhost:3000/contenido/genero/nombre/drama

### Crear un nuevo contenido
POST http://localhost:3000/contenido
Content-Type: application/json

{ 
   "poster":"./posters/99.jpg",
   "titulo":"outlander",
   "id_categoria":1,
   "resumen":"Outlander es una serie de televisión británica-estadounidense de drama histórico basada en la saga de novelas homónima de Diana Gabaldon.",
   "temporada":"7",
   "duracion":null,
   "trailer":"https://youtu.be/1Q_ixUVIbcg"
  
}
### Crear un actor de serie Outlander
POST http://localhost:3000/contenido/actor
Content-Type: application/json

{
  "nombre": "Sam",
  "apellido": "Heughan"
}

###unir contenido y actor en contenido_actor
POST http://localhost:3000/contenido/52/actor/360

###  Actualizar un contenido
PUT http://localhost:3000/contenido/52
Content-Type: application/json

{
   "poster":"./posters/99.jpg",
   "titulo":"Outlander",
   "id_categoria":1,
   "resumen":"Outlander es una serie de televisión británica-estadounidense de drama histórico basada en la saga de novela.Outlander es una serie de romance histórico y viajes en el tiempo sobre la enfermera británica Claire Randall, que viaja en el tiempo desde el siglo XX hasta la Escocia del siglo XVII . Allí encuentra el amor y la aventura con el apuesto Jamie Fraser, un guerrero de las Tierras Altas.",
   "temporada":"6",
   "duracion":null,
   "trailer":"https://youtu.be/1Q_ixUVIbcg"
}

### Actualizar parcialmente contenido temporada:
PATCH http://localhost:3000/contenido/52
Content-Type: application/json

{
   "temporada":"8"
}
###  relacionar entre el contenido y genero en tabla contenido_genero
POST http://localhost:3000/contenido/52/genero/nombre/Drama

### crear un nueva palabra de busqueda
POST http://localhost:3000/contenido/busqueda
Content-Type: application/json

{
   "palabras_de_busqueda":"montañas"
}
### relacionar contenido y busqueda en tabla contenido_busqueda
POST http://localhost:3000/contenido/52/busqueda/52

### delete un contenido por ID
DELETE http://localhost:3000/contenido/54
 